### ISSUE TITLE
TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by portrayer** [commissure/redbox-react#100]
in `mapOnConstruction` (index.js, line 48):
`const isWebpackEval = stackLines[1].search(/\(webpack:\/{3}/) !== -1`

sometimes error.stack doesn't contain '\n', such as SyntaxError thrown by `Response.prototype.json`

**Comment by borela** [comment]
Can you post an example of the stack's contents ?

**Comment by portrayer** [comment]
try this:
`fetch(location.href).then(res => res.json()).catch(console.dir)`
