### ISSUE TITLE
[SSR] renderToString returns <!-- react-empty: 1 -->

### ISSUE THREAD

**Issue by kimjuny** [commissure/redbox-react#106]
> react@15.6.1

> redbox@1.4.1 ~ 1.5.0

Has this problem been solved? https://github.com/commissure/redbox-react/pull/99 I've tried redbox@1.4.1 ~ 1.5.0, ssr always returns `<!-- react-empty: 1 -->`

```javascript
const RedBox = require('redbox-react').default;
content = renderToString(<RedBox error={new Error()} />);
console.log(content); // <!-- react-empty: 1 -->
```

**Comment by kimjuny** [comment]
Never mind, this will work.

```javascript
const RedBox = require('redbox-react').RedBoxError;
content = renderToString(<RedBox error={e} />);
```

**Comment by rubenw** [comment]
Could we re-open this? I'd like to use the `default` module instead of the actual redbox component. Right now, I'm ending up with an empty content string (react@16.0.0 and redbox@1.5.0)

**Comment by matteocng** [comment]
Confirmed empty content string (react@15.6.2 and redbox@1.5.0) with @kimjuny's first example, and that the second example is working.
