### ISSUE TITLE
Duplicate react ids generated when redbox is inside an 'a' tag

### ISSUE THREAD

**Issue by hoegrammer** [commissure/redbox-react#20]
When an error is thrown in a component that is inside an 'a' tag, this causes nested links due to the link in the redbox.

In Chrome this causes both 'a' tags to be given the same class which causes duplicate React IDs as noted here https://github.com/facebook/react/issues/4120 especially in https://github.com/facebook/react/issues/4120#issuecomment-111754614

**Comment by hoegrammer** [comment]
This only happens when the rendering is done on the server.

**Comment by mxlje** [comment]
Closing because there hasn’t been any activity on this in a while. Please reopen if somebody still having problems.
