### ISSUE TITLE
Moving to Commissure org

### ISSUE THREAD

**Issue by davidpfahler** [commissure/redbox-react#69]
My buddy @mxlje and I have created a new [GitHub org called "Commissure"](https://github.com/commissure/). In order to consolidate our open-source efforts, we would like to move redbox-react to this new org. This should help accelerate its progress and make it clear that this is a community oriented, open-source project and has nothing to do with one of our previous experiments, i.e. KeywordBrain.

As far as I know, GitHub will simple redirect everything once we move the repo. Everything should work just fine. However, I want your feedback and possible objections to this move. I don't want anyone to be adversely affected by this.

Please let me know what you think about this.

**Comment by mxlje** [comment]
As there have been no objections to this so far, the move will be done tomorrow.
