### ISSUE TITLE
Error running with React 15.4

### ISSUE THREAD

**Issue by jasanst** [commissure/redbox-react#73]
If you have react@15.4.0-rc.4 installed redbox-react will fail with a file not found error.

    ERROR in ./~/redbox-react/~/react-dom/index.js
    Module not found: Error: Can't resolve 'react/lib/ReactDOM'

Redbox-react installs 15.3 which depends on the project level React version, 15.4 has changed the structure and this file is now in ReactDOM itself.

**Comment by wellyshen** [comment]
I have the same problem :(

**Comment by gaearon** [comment]
This is because `redbox-react` should have included `react-dom` in `peerDependencies` rather than `dependencies`.

If you have this issue, just delete `node_modules/redbox-react/node_modules/react-dom` and it will work.
