### ISSUE TITLE
IE11 React 15.4 issue

### ISSUE THREAD

**Issue by DimitryDushkin** [commissure/redbox-react#82]
On IE11 I got error:
```
 Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `RedBoxError`.
```

Wonder why it's problem only in IE...

**Comment by davidpfahler** [comment]
Do you understand what that error is supposed to mean in context of Redbox?

**Comment by DimitryDushkin** [comment]
Looks like for some reason https://github.com/commissure/redbox-react/blob/master/src/index.js#L72 returns object
I really do not understand why.

**Comment by davidpfahler** [comment]
Weird. IE11 is kind of hard for me to debug, but I am happy to review PRs.

**Comment by nickw444** [comment]
Also having this same issue 😞

**Comment by gaearon** [comment]
Appears related: https://github.com/facebook/react/issues/8379.
Can you share a reproducing example?

**Comment by tanepiper** [comment]
I'm having the same issue.  However I have two apps - one running 15.1.0 and one running 15.4.0, on a more recent update path.

https://www.votesforschools.com/  (15.1.0)
https://admin.votesforschools.com/ (15.4.0)

In each case in IE11 the exception is this:

https://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]=

Which outputs:

```
Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}).
```

However this is only happening in deployed production.  If I do a production build locally and serve it from Python SimpleHTTPServer this exception does not trigger

I'm not using Redbox.

I just want to report this, but as of tomorrow I'm rolling off this project as I'm starting a new job in the new year so I won't have access to the source code after this.

**Comment by DimitryDushkin** [comment]
It's not redbox related. Adding Symbol polyfill is the fix — https://github.com/thejameskyle/babel-react-optimize/issues/16#issuecomment-263519239

**Comment by davidpfahler** [comment]
@DimitryDushkin Thanks!

**Comment by gaearon** [comment]
As for IE11 problem, also see this: https://github.com/facebook/react/issues/8379#issuecomment-264858787.
