### ISSUE TITLE
Lower the z-index

### ISSUE THREAD

**Issue by sontek** [commissure/redbox-react#83]
Currently redbox-react is using the highest possible z-index which makes it so tools like `react-devtools` and the monitors like:

https://github.com/gaearon/redux-devtools-dock-monitor
https://github.com/gaearon/redux-devtools-log-monitor

Can't be used with it.

This makes `redbox-react` very difficult to use in a dev environment because you can't inspect your redux state.    Any chance you can lower it to something that the other tools can go above?

**Comment by sontek** [comment]
A workaround is to override `style` but it does a shallow merge show you have to override all `redbox` styles for it to work

**Comment by mxlje** [comment]
Hey @sontek, thank you for opening an issue with `redbox-react`!

The issue with the `z-index` and what its proper value should be has come up many times in the past, most recently not two months ago (#78), which is when we changed the value to what it is right now (in response to another layout bug).

I understand your point (and we might have gone a little overboard with the max int as nobody else can go higher now), but the decentralized nature of all these different packages and dev tools makes it hard to keep everything in sync as new layout issues will arise regularly.

I was going to ask if you could suggest a better value and help drive the discussion here https://github.com/gaearon/redux-devtools/issues/329, but while I was typing this you closed this issue already by providing a workaround. I assume this is no longer a problem for you then?

We’re happy to improve `redbox-react`s interoperability with other dev tools (after all it is just one of many and they should all work together), but simply changing the `z-index` to a new value that works _right now_ will most certainly require it to be changed _again_ later on once a new package shows up.

**Comment by sontek** [comment]
@mxlje Yeah, I think the workaround I posted is good enough.  It would be nice redbox didn't go to the highest available option so people would have the option to override it but in the end with all the different tools around that a `style` override would be necessary somewhere.
