### ISSUE TITLE
Support other types of sourcemaps

### ISSUE THREAD

**Issue by frux** [commissure/redbox-react#84]
If I'm not mistaken RedBox supports only ``eval`` type of sourcemaps in webpack. But ``eval`` sourcemaps is very poor because 

> it doesn't display line numbers correctly since it gets mapped to transpiled code instead of the original code.

Is it possible to support at least ``eval-source-map``?

**Comment by davidpfahler** [comment]
Off the top of my head, I don't know how to make it support that, but if you want to send a pull request I'd be happy to check it out.

**Comment by borela** [comment]
@frux You may want to check [this pull request](https://github.com/commissure/redbox-react/pull/94)

**Comment by davidpfahler** [comment]
Fixed by #94

**Comment by LachlanStuart** [comment]
I've made a PR to fix an issue I was having with having mixed stack traces: https://github.com/commissure/redbox-react/pull/97
