### ISSUE TITLE
It seems dep is missing

### ISSUE THREAD

**Issue by steida** [commissure/redbox-react#89]
<img width="341" alt="screen shot 2017-04-08 at 19 41 25" src="https://cloud.githubusercontent.com/assets/66249/24831090/6f7b9b4a-1c93-11e7-8940-805de3dbf4fe.png">

**Comment by davidpfahler** [comment]
@steida did you `npm install`? We just updated to support react `15.0.1` so you might need to do `npm install redbox-react`.

**Comment by steida** [comment]
Sorry, I had fixed dependencies "react": "~15.4.2" and "react-dom": "~15.4.2".
